version: '3.1'

services:
  daemon:
    build: .
    container_name: minicloud-daemon
    ports:
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - minicloud
    depends_on:
      - distribution
    links:
      - "distribution"
  distribution:
    build: distribution
    container_name: minicloud-registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /var/lib/registry:/var/lib/registry
    networks:
      - minicloud
networks:
  minicloud:
    driver: bridge
    enable_ipv6: false
    attachable: true
    labels:
      minicloud-managed: true